#include <stdint.h>
#include <string.h>

#define VGA_COLOR_ATTRIB(FgColor, BgColor) (BgColor << 4) | FgColor

enum vga_colors {
    VGA_COLOR_BLACK = 0x0,
    VGA_COLOR_BLUE = 0x1,
    VGA_COLOR_GREEN = 0x2,
    VGA_COLOR_CYAN = 0x3,
    VGA_COLOR_RED = 0x4,
    VGA_COLOR_MAGENTA = 0x5,
    VGA_COLOR_BROWN = 0x6,
    VGA_COLOR_LIGHT_GRAY = 0x7,
    VGA_COLOR_DARK_GAY = 0x8,
    VGA_COLOR_LIGHT_BLUE = 0x9,
    VGA_COLOR_LIGHT_GREEN = 0xA,
    VGA_COLOR_LIGHT_CYAN = 0xB,
    VGA_COLOR_LIGHT_RED = 0xC,
    VGA_COLOR_LIGHT_MAGENTA = 0xD,
    VGA_COLOR_LIGHT_YELLOW = 0xE,
    VGA_COLOR_WHITE = 0xF,
};

void _start() {
    uint8_t message[] = {
        'B', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_BLUE, VGA_COLOR_BLACK),
        'e', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_BLUE, VGA_COLOR_BLACK),
        'r', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_BLUE, VGA_COLOR_BLACK),
        'r', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_BLUE, VGA_COLOR_BLACK),
        'y', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_BLUE, VGA_COLOR_BLACK),
        'O', VGA_COLOR_ATTRIB(VGA_COLOR_WHITE,      VGA_COLOR_BLACK),
        'S', VGA_COLOR_ATTRIB(VGA_COLOR_WHITE,      VGA_COLOR_BLACK),
        ' ', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
        'v', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
        '0', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
        '.', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
        '1', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
        '.', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
        '0', VGA_COLOR_ATTRIB(VGA_COLOR_LIGHT_GRAY, VGA_COLOR_BLACK),
    };

    uint16_t* video_ram = (uint16_t*)0xB8000;
    memcpy(video_ram, &message, 28);

    while (1) {}
}
